package sn.axa.apiaxacnaas.util;

public enum ClaimDocumentType {
    RAPPORT_MEDICAL,
    FACTURE_ORDONNACE,
    FRAIS_PHARMACEUTIQUES,
    PIECE_IDENTITE,
    CERTIFICAT_INVALIDITE,
    CERTIFICAT_DECES,
    DECHARGE_HOSPITALISATION,
    AUTRE,
}
