package sn.axa.apiaxacnaas.util;

public enum ClaimDocumentType {
    PIECE_IDENTITE,
    PIECE_IDENTITE_INVALIDITE,
    PIECE_IDENTITE_FUNERAIRE,
    PIECE_IDENTITE_HOSPICASH,
    CERTIFICAT_INVALIDITE,
    CERTIFICAT_DECES,
    DECHARGE_HOSPITALISATION,

}
