package sn.axa.apiaxacnaas.util;

public enum ClaimDocumentType {
    PIECE_IDENTITE,
    PIECE_IDENTITE_RECTO_INVALIDITE,
    PIECE_IDENTITE_VERSO_INVALIDITE,
    PIECE_IDENTITE_RECTO_FUNERAIRE,
    PIECE_IDENTITE_VERSO_FUNERAIRE,
    PIECE_IDENTITE_RECTO_HOSPICASH,
    PIECE_IDENTITE_VERSO_HOSPICASH,
    CERTIFICAT_INVALIDITE,
    CERTIFICAT_DECES,
    DECHARGE_HOSPITALISATION,
}
